export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIl";

export const PRODUCT_DETAILS_REQUEST = "ALL_PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "ALL_PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILED = "ALL_PRODUCT_DETAILS_FAILED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
